# Generated by Django 4.0.6 on 2022-07-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=64)),
                ('starting_bid', models.FloatField()),
                ('listing_description', models.CharField(max_length=240)),
            ],
        ),
    ]
